# ML Assignment 02
### Dataset: House Price Prediction Dataset
### Total Marks: 100

---

---

**Question Dataset Link:** https://www.kaggle.com/datasets/prokshitha/home-value-insights

## Student Information

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDRegressor, LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score

In [ ]:
df = pd.read_csv("house_price_regression_dataset.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        1000 non-null   int64
 1   Num_Bedrooms          1000 non-null   int64
 2   Num_Bathrooms         1000 non-null   int64
 3   Year_Built            1000 non-null   int64
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   int64
 6   Neighborhood_Quality  1000 non-null   int64
 7   House_Price           1000 non-null   float64
dtypes: float64(2), int64(6)
memory usage: 62.6 KB

---
## Question 1 (10 Marks)

Load the House Price dataset and display:
- Dataset shape
- First 10 rows
- 5 random samples

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.head(10)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
5,3944,5,3,1990,2.475930,2,8,8.797970e+05
6,3671,1,2,2012,4.911960,0,1,8.144279e+05
7,3419,1,1,1972,2.805281,1,1,7.034131e+05
8,630,3,3,1997,1.014286,1,8,1.738750e+05
9,2185,4,2,1981,3.941604,2,5,5.041765e+05

In [ ]:
df.sample(5)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
632,1399,2,2,2003,1.680543,0,3,310271.263669
377,1395,4,2,1973,3.305650,0,2,336073.521599
381,2431,1,3,2009,1.544251,0,10,538851.893395
665,1138,2,3,2022,1.959556,2,9,315357.481018
513,4127,5,2,1992,1.026156,2,1,909713.435001

---
## Question 2 (10 Marks)

Handle missing values and perform feature engineering:
- Impute missing numerical values using `SimpleImputer` with mean strategy
- Impute missing categorical values using most frequent strategy
- Drop columns with more than 50% missing values
- Perform train-test split with `test_size=0.2` and `random_state=42`

Display the shape of final train and test sets.

In [ ]:
missing = df.isnull().sum()
drop_cols = missing[missing > len(df) * 0.5].index
df.drop(drop_cols, axis=1, inplace=True)

X = df.drop("House_Price", axis=1)
y = df["House_Price"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)

In [ ]:
num_cols = ["Square_Footage", "Num_Bedrooms", "Num_Bathrooms"]
num_imputer = SimpleImputer(strategy = "mean")

X_train[num_cols] = num_imputer.fit_transform(X_train[num_cols])
X_test[num_cols] = num_imputer.transform(X_test[num_cols])

In [ ]:
cat_cols = ["Neighborhood_Quality"]
cat_imputer = SimpleImputer(strategy = "most_frequent")

X_train[cat_cols] = cat_imputer.fit_transform(X_train[cat_cols])
X_test[cat_cols] = cat_imputer.transform(X_test[cat_cols])

In [ ]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (800, 7)
X_test : (200, 7)
y_train: (800,)
y_test : (200,)

---
## Question 3 (20 Marks)

Implement **Simple Linear Regression** using **only NumPy** (no Scikit-Learn allowed):
- Compute slope (`m`) and intercept (`c`) using the Batch Gradient Descent
- Predict values for the test set
- Print the learned `m` and `c` values

Use `Square_Footage` as feature (X) and `House_Price` as target (y).

In [ ]:
X = df["Square_Footage"].values
y = df["House_Price"].values
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
def calculate_gradient(X, y, m, c):
    n = X.shape[0]

    dj_dm = 0.0
    dj_dc = 0.0

    for i in range(n):
        prediction = m * X[i] + c
        error = prediction - y[i]
        dj_dm = dj_dm + (error * X[i])
        dj_dc = dj_dc + error

    return dj_dm / n, dj_dc / n

In [ ]:
def gradient_descent(X, y, m, c, alpha=0.001, max_iter=1000):
    for i in range(max_iter):
        dj_dm, dj_dc = calculate_gradient(X, y, m, c)
        m = m - alpha * dj_dm
        c = c - alpha * dj_dc

    return m, c, max_iter

In [ ]:
m = 0
c = 0

parameters = gradient_descent(X_train, y_train, m, c)
m = parameters[0]
c = parameters[1]

y_pred = m * X_test + c

/tmp/ipykernel_991/4013117833.py:10: RuntimeWarning: overflow encountered in scalar add
  dj_dm = dj_dm + (error * X[i])
/tmp/ipykernel_991/2663843701.py:4: RuntimeWarning: invalid value encountered in scalar subtract
  m = m - alpha * dj_dm

In [ ]:
print(np.round(y_pred[:10], 4))

[ 851409.1473  507641.0339  985990.375  1022654.7065  760698.1337
  765782.3164 1005039.0963  903407.7818  797971.1884  888850.43  ]

In [ ]:
print("m =", m)
print("c =", c)

m = nan
c = nan

---
## Question 4 (10 Marks)

Build a **ColumnTransformer** that applies:
- `StandardScaler` on numerical columns: `Square_Footage`, `Num_Bedrooms`, `Num_Bathrooms`
- `OneHotEncoder` on categorical column: `Neighborhood_Quality`

In [ ]:
num_cols = ["Square_Footage", "Num_Bedrooms", "Num_Bathrooms"]
cat_cols = ["Neighborhood_Quality"]

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), num_cols),
        ('cat', OneHotEncoder(), cat_cols)
    ]
)

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [ ]:
model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("regressor", SGDRegressor())
    ]
)

In [ ]:
X = df.drop("House_Price", axis=1)
y = df["House_Price"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42
)
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Neighborhood_Quality'])])),
                ('regressor', SGDRegressor())])

In [ ]:
y_pred = model.predict(X_test)

print(f"RMSE: {round(root_mean_squared_error(y_test, y_pred), 4)}")
print(f"R2: {round(r2_score(y_test, y_pred), 4)}")

RMSE: 29088.4969
R2: 0.9869

In [ ]:
print("Actual:")
print(y_test.head(10))

print("Predicted:")
print(y_pred[:10])

Actual:
521    9.010005e+05
737    4.945375e+05
740    9.494042e+05
660    1.040389e+06
411    7.940100e+05
678    7.240336e+05
626    9.984392e+05
513    9.097134e+05
859    7.926815e+05
136    9.474908e+05
Name: House_Price, dtype: float64
Predicted:
[ 851409.14732655  507641.0338697   985990.37503164 1022654.70653384
  760698.13365681  765782.31638091 1005039.09634383  903407.78177236
  797971.18840959  888850.4300377 ]

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [ ]:
model = Pipeline([
    ("preprocessor", preprocessor),
    ("regressor", LinearRegression())
])

In [ ]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Neighborhood_Quality'])])),
                ('regressor', LinearRegression())])

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
print(f"RMSE: {round(root_mean_squared_error(y_test, y_pred), 4)}")
print(f"R2: {round(r2_score(y_test, y_pred), 4)}")

RMSE: 29093.0752
R2: 0.9869

In [ ]:
print("Actual:")
print(y_test.head(10))

print("Predicted:")
print(y_pred[:10])

Actual:
521    9.010005e+05
737    4.945375e+05
740    9.494042e+05
660    1.040389e+06
411    7.940100e+05
678    7.240336e+05
626    9.984392e+05
513    9.097134e+05
859    7.926815e+05
136    9.474908e+05
Name: House_Price, dtype: float64
Predicted:
[ 851409.14732655  507641.0338697   985990.37503164 1022654.70653384
  760698.13365681  765782.31638091 1005039.09634383  903407.78177236
  797971.18840959  888850.4300377 ]

---
## Question 7 (10 Marks) (You have to explore the topic and use the equation via Numpy)
### Dont use LLMs , You can use Documentation

Implement **Multiple Linear Regression** using **only NumPy**:
- Pick random 100 datas from the dataset
- Use the Normal Equation: `θ = (XᵀX)⁻¹ Xᵀy`
- Use `Square_Footage`, `Num_Bedrooms`, and `Num_Bathrooms` as features
- Print the learned coefficients (θ values)

In [ ]:
random_data = df.sample(100)